# Simple workflow for deploying static content to GitHub Pages
name: PReviewer

on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:

jobs:
  # Single deploy job since we're just deploying
  reviewer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: PR Review
        uses: RiceBen/oh-llama-review-action@eb60150e883691015f45c74ef1d95d67b79b1f8e
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          model: llama3.2:3b
