# Simple workflow for deploying static content to GitHub Pages
name: PReviewer

on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:

jobs:
  # Single deploy job since we're just deploying
  reviewer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: PR Review
        uses: RiceBen/MyPReviewer@a8042a4b3bac485d87c3c5e80d3a59c91f4386f6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          model: llama3