# Simple workflow for deploying static content to GitHub Pages
name: PReviewer

on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:

jobs:
  # Single deploy job since we're just deploying
  reviewer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: PR Review
        uses: RiceBen/MyPReviewer@ed390dab0eb3aa4c2698cff9a6c72f4fe79f0b59
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          model: llama3