# Simple workflow for deploying static content to GitHub Pages
name: PReviewer

on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:

jobs:
  # Single deploy job since we're just deploying
  reviewer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: PR Review
        uses: RiceBen/oh-llama-review-action@c52d6ff7d2a39fb89b5bdd037b6c2161c7f3b65c
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          model: llama3.2:3b
